"""Initial migration

Revision ID: 842179b64ff4
Revises: f16597e73665
Create Date: 2023-11-20 07:14:40.737836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '842179b64ff4'
down_revision = 'f16597e73665'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=25), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
